# GreenEdge-5G — Makefile
# Provides single-command reproducibility for training, evaluation, and quality checks.
#
# Usage (PowerShell with Make available, or Linux/macOS):
#   make all           — lint + test + train + evaluate + multi-seed summary
#   make train         — train PPO (500k steps, recommended)
#   make evaluate      — single-seed evaluation (seed=0, 200 episodes)
#   make multiseed     — multi-seed evaluation (seeds 0 42 123, writes results_summary.json)
#   make lint          — run ruff linter
#   make test          — run pytest
#   make dashboard     — launch Streamlit dashboard
#   make clean         — remove __pycache__ and .pyc files

PYTHON   := .venv/Scripts/python
RUFF     := .venv/Scripts/ruff
PYTEST   := .venv/Scripts/pytest
STREAMLIT := .venv/Scripts/streamlit

EXPERIMENTS := experiments
POLICY      := $(EXPERIMENTS)/policy.zip

.PHONY: all lint test train evaluate multiseed dashboard plots clean

# ---------------------------------------------------------------------------
all: lint test train evaluate multiseed
	@echo ""
	@echo "=== GreenEdge-5G full pipeline complete ==="
	@echo "Results : $(EXPERIMENTS)/results.json"
	@echo "Summary : $(EXPERIMENTS)/results_summary.json"
	@echo "Plots   : $(EXPERIMENTS)/plots_reward.png"
	@echo "         $(EXPERIMENTS)/plots_tradeoff.png"

# ---------------------------------------------------------------------------
lint:
	$(RUFF) check greenedge/ tests/

# ---------------------------------------------------------------------------
test:
	$(PYTEST) tests/ -v --tb=short

# ---------------------------------------------------------------------------
train:
	$(PYTHON) -m greenedge.rl.train \
		--algo ppo \
		--steps 500000 \
		--out $(EXPERIMENTS)/policy.zip
	@echo "[make] Training complete -> $(POLICY)"

# ---------------------------------------------------------------------------
evaluate:
	$(PYTHON) -m greenedge.rl.evaluate \
		--episodes 200 \
		--seed 0 \
		--policy $(POLICY) \
		--out $(EXPERIMENTS)
	@echo "[make] results.json updated"

# ---------------------------------------------------------------------------
multiseed:
	$(PYTHON) -m greenedge.rl.evaluate \
		--episodes 200 \
		--seeds 0 42 123 \
		--policy $(POLICY) \
		--out $(EXPERIMENTS)
	@echo "[make] results_summary.json updated"

# ---------------------------------------------------------------------------
plots: evaluate
	@echo "[make] Plots already generated by evaluate step."

# ---------------------------------------------------------------------------
dashboard:
	$(STREAMLIT) run greenedge/dashboard/app.py

# ---------------------------------------------------------------------------
clean:
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -name "*.pyc" -delete 2>/dev/null || true
	@echo "[make] Clean done."
